### ISSUE TITLE
Issue with parsing double from CSV

### ISSUE THREAD

**Issue by RomantsovArtur** [badoo/pyexasol#51] opened 2020-05-26 09:45 UTC
Hi,

I faced an issue while working with library functionality
`conn.import_from_file(file_obj, update_table_name)`
if we have double value in CSV file like "0.0272" it will become 0.027200000000000002 in exasol.

I can't see ability to setup format for CSV like that: (1..57,58 format='999999999999999.999999', 59..93)
To query, that was produced by library:
```
IMPORT INTO tmp_transactions_7220673 FROM CSV
AT 'http://27.1.0.10:46363' FILE '000.gz'
```

**Comment by wildraid** [comment] 2020-05-26 11:40
Hello,

Please note, this behaviour is not related to PyEXASOL import, but to DOUBLE PRECISION implementation and storage in general.

Please try to run the following basic example:

```
stmt = C.execute("SELECT CAST('0.0272' AS DOUBLE PRECISION)")
print(stmt.fetchall())
```

The debug + response is following:

```
2020-05-26 12:38:10.350 [WebSocket request #4]
{
    "command": "execute",
    "sqlText": "SELECT CAST('0.0272' AS DOUBLE PRECISION)"
}
2020-05-26 12:38:10.384 [WebSocket response #4]
{
    "status": "ok",
    "responseData": {
        "results": [
            {
                "resultType": "resultSet",
                "resultSet": {
                    "numColumns": 1,
                    "numRows": 1,
                    "numRowsInMessage": 1,
                    "columns": [
                        {
                            "name": "CAST('0.0272' AS DOUBLE)",
                            "dataType": {
                                "type": "DOUBLE"
                            }
                        }
                    ],
                    "data": [
                        [
                            0.027200000000000002
                        ]
                    ]
                }
            }
        ],
        "numResults": 1
    }
}
[(0.027200000000000002,)]
```

**Comment by wildraid** [comment] 2020-05-26 11:41
If you wish to avoid the non-precision calculation, you may simply use DECIMAL datatype of appropriate size.

For example:

```
stmt = C.execute("SELECT CAST('0.0272' AS DECIMAL(10,4))")
```

Will give you:

```
2020-05-26 12:41:12.993 [WebSocket request #4]
{
    "command": "execute",
    "sqlText": "SELECT CAST('0.0272' AS DECIMAL(10,4))"
}
2020-05-26 12:41:13.025 [WebSocket response #4]
{
    "status": "ok",
    "responseData": {
        "results": [
            {
                "resultType": "resultSet",
                "resultSet": {
                    "numColumns": 1,
                    "numRows": 1,
                    "numRowsInMessage": 1,
                    "columns": [
                        {
                            "name": "CAST('0.0272' AS DECIMAL(10,4))",
                            "dataType": {
                                "type": "DECIMAL",
                                "precision": 10,
                                "scale": 4
                            }
                        }
                    ],
                    "data": [
                        [
                            "0.0272"
                        ]
                    ]
                }
            }
        ],
        "numResults": 1
    }
}
[('0.0272',)]
```

Hope it helps!

**Comment by RomantsovArtur** [comment] 2020-05-26 12:04
Yes, I should have mentioned that I'm speaking only about **import statement** that generated by pyexasol

select cast('0.0272' as double) from dual;
0.027200000000000002
select cast(0.0272 as double) from dual;
0.0272

The idea is to help exasol to determine that field shouldn't be interpreted as a string by explicit a number format in import statement. It can be done manually by calling statement like that:
IMPORT INTO table FROM LOCAL CSV FILE 'table_path' (1..2,3 format='999999999.999');

https://docs.exasol.com/loading_data/file_formats.htm ( Numbers part of page)
https://docs.exasol.com/sql_references/formatmodels.htm#DateTimeFormat (Numeric Format Model part of page)

Is that a way to add this part (1..2,3 format='999999999.999') to import query generated by library?

**Comment by wildraid** [comment] 2020-05-26 15:59
Ok, it's a very interesting case. I've managed to reproduce it.

I'll raise a ticket for Exasol support. I suspect string to double conversion is not performed correctly, but it is not so obvious in other SQL clients (e.g. ExaPlus).

We'll try to find a more generic solution or fix the default behaviour.

---

About the "format" block in IMPORT SQL. It's not supported at this moment, since this syntax is not very flexible and generally leads to other unintended consequences. It is possible to implement, but it may lead to more problems down the road.

---

In the meantime, can you use one of following workarounds?

1) Switch to DECIMAL datatype for target table.
2) Import into "staging" table first with DECIMAL datatype, but move data into target table with DOUBLE datatype.
3) Apply UPDATE in the same transaction after IMPORT, normalising DOUBLES to required format.

I'll come back to you when I have more info.

Thank you for finding this!

**Comment by RomantsovArtur** [comment] 2020-05-26 17:15
The workarounds are working, but I'm looking for more generic solution for double and pyexasol library without additional step.

Thank you very much for investigating that. Will wait for answer from exasol support as well.

**Comment by wildraid** [comment] 2020-05-28 15:28
I just want to give a quick update on this. 

Exasol support is still investigating the issue. It is not connected with PyEXASOL specifically, but with treatment of VARCHAR -> DOUBLE conversion in general. If developers decide to fix it at source, it might break some backwards compatibility.

I'll keep you updated.

**Comment by RomantsovArtur** [comment] 2020-05-28 16:05
Yeah, I can see it by running simple queries in exasol.

```
select cast('0.0272' as double) from dual;
0.027200000000000002
select cast(0.0272 as double) from dual;
0.0272
```

Can we do something with this:
`About the "format" block in IMPORT SQL. It's not supported at this moment, since this syntax is not very flexible and generally leads to other unintended consequences. It is possible to implement, but it may lead to more problems down the road.`

may I can create PR or something?

**Comment by wildraid** [comment] 2020-05-29 16:42
PR is definitely possible, but:

1) `csv_cols` option is generally quite ugly and not very flexible. We normally recommend users to create their own proper data transformation and layer and send "clean" and pre-formatted data to Exasol. It won't work in this case, but it will work in most of other common use cases.

2) Syntax of `csv_cols` is complex. We have individual column numbers, ranges and mixed formats. If we just pass a string directly to SQL, it will lead to SQL-injection. If we create a query builder, it will be complex as well.

3) This problems affects all kinds of IMPORT, not only PyEXASOL. So even if we provide an obscure way to fix it here, 99% of people will not be aware of the problem. And some people who will be aware, they'll have to write a complex code and provide number formatting for every DOUBLE column manually.

---

So I'd rather give a chance for Exasol support to come out with their vision of general fix for this problem. It can be some sort of global SQL changing session parameter, or command line parameter, or just a fix in the ETL process code.

Let's see how it goes. It should not take long, I expect some feedback early next week.

**Comment by wildraid** [comment] 2020-05-30 07:45
Ok, so here is the response from support, which is quite interesting:

> This is a disadvantage when using double values.  Those inaccuracies are not unexpected when dealing with DOUBLEs. As DOUBLE is an approximative data type, some values cannot be stored exactly. Double is based on a number representation of base 2 compared to base 10 for our exact numeric types. This means that even the same exact numeric number might get a different double representation when converting to double, as you can see for the following example where always the same number 0.0272 (and for comparison 0.272) is casted to double from different Decimal(X,X)-types:

```
create or replace table t(d5 decimal(5,5), d6 decimal(6,6), d7 decimal(7,7), d8 decimal(8,8), d9 decimal(9,9), d10 decimal(10,10), d11 decimal(11,11), d12 decimal(12,12), d13 decimal(13,13), d14 decimal(14,14), d15 decimal(15,15), d16 decimal(16,16), d17 decimal(17,17), d18 decimal(18,18), d19 decimal(19,19), d20 decimal(20,20), d21 decimal(21,21), d22 decimal(22,22), d23 decimal(23,23), d24 decimal(24,24), d25 decimal(25,25), d26 decimal(26,26), d27 decimal(27,27), d28 decimal(28,28), d29 decimal(29,29), d30 decimal(30,30), d31 decimal(31,31), d32 decimal(32,32), d33 decimal(33,33), d34 decimal(34,34), d35 decimal(35,35), d36 decimal(36,36));
insert into t values (0.272, 0.272, 0.272, 0.272, 0.272, 0.272, 0.272, 0.272, 0.272, 0.272, 0.272, 0.272, 0.272, 0.272, 0.272, 0.272, 0.272, 0.272, 0.272, 0.272, 0.272, 0.272, 0.272, 0.272, 0.272, 0.272, 0.272, 0.272, 0.272, 0.272, 0.272, 0.272);
insert into t values (0.0272, 0.0272, 0.0272, 0.0272, 0.0272, 0.0272, 0.0272, 0.0272, 0.0272, 0.0272, 0.0272, 0.0272, 0.0272, 0.0272, 0.0272, 0.0272, 0.0272, 0.0272, 0.0272, 0.0272, 0.0272, 0.0272, 0.0272, 0.0272, 0.0272, 0.0272, 0.0272, 0.0272, 0.0272, 0.0272, 0.0272, 0.0272);
select cast(d5 as double) doub5, cast(d6 as double) doub6, cast(d7 as double) doub7, cast(d8 as double) doub8, cast(d9 as double) doub9, cast(d10 as double) doub10, cast(d11 as double) doub11, cast(d12 as double) doub12, cast(d13 as double) doub13, cast(d14 as double) doub14, cast(d15 as double) doub15, cast(d16 as double) doub16, cast(d17 as double) doub17, cast(d18 as double) doub18, cast(d19 as double) doub19, cast(d20 as double) doub20, cast(d21 as double) doub21, cast(d22 as double) doub22, cast(d23 as double) doub23, cast(d24 as double) doub24, cast(d25 as double) doub25, cast(d26 as double) doub26, cast(d27 as double) doub27, cast(d28 as double) doub28, cast(d29 as double) doub29, cast(d30 as double) doub30, cast(d31 as double) doub31, cast(d32 as double) doub32, cast(d33 as double) doub33, cast(d34 as double) doub34, cast(d35 as double) doub35, cast(d36 as double) doub36 from t;
```

> If you look at a string representation we have to use an internal decimal type as an intermediate type, e.g. the smallest one who could hold the number. There is a difference between importing into a double column and importing into a decimal column (which uses the same decimal place for all values) and then converting to double.
> 
> For exact numeric conversions, we recommend to use Double Precision **(comment: probably a mistake, should be Decimal instead)** data type.
> 
> For little bit more information see:
> 
> https://www.exasol.com/support/browse/SOL-102
> https://docs.exasol.com/sql_references/data_types/datatypedetails.htm
>  

Here is the result of SQL above:

```
'[{"DOUB5": 0.272, "DOUB6": 0.272, "DOUB7": 0.272, "DOUB8": 0.272, "DOUB9": 0.272, "DOUB10": 0.272, "DOUB11": 0.272, "DOUB12": 0.272, "DOUB13": 0.272, "DOUB14": 0.272, "DOUB15": 0.272, "DOUB16": 0.272, "DOUB17": 0.272, "DOUB18": 0.272, "DOUB19": 0.272, "DOUB20": 0.272, "DOUB21": 0.272, "DOUB22": 0.272, "DOUB23": 0.272, "DOUB24": 0.272, "DOUB25": 0.27199999999999996, "DOUB26": 0.27199999999999996, "DOUB27": 0.27199999999999996, "DOUB28": 0.272, "DOUB29": 0.272, "DOUB30": 0.272, "DOUB31": 0.272, "DOUB32": 0.272, "DOUB33": 0.272, "DOUB34": 0.272, "DOUB35": 0.272, "DOUB36": 0.27199999999999996}, {"DOUB5": 0.0272, "DOUB6": 0.0272, "DOUB7": 0.0272, "DOUB8": 0.0272, "DOUB9": 0.0272, "DOUB10": 0.0272, "DOUB11": 0.0272, "DOUB12": 0.0272, "DOUB13": 0.0272, "DOUB14": 0.0272, "DOUB15": 0.0272, "DOUB16": 0.0272, "DOUB17": 0.0272, "DOUB18": 0.0272, "DOUB19": 0.0272, "DOUB20": 0.0272, "DOUB21": 0.0272, "DOUB22": 0.0272, "DOUB23": 0.027200000000000002, "DOUB24": 0.027200000000000002, "DOUB25": 0.0272, "DOUB26": 0.0272, "DOUB27": 0.0272, "DOUB28": 0.0272, "DOUB29": 0.027200000000000005, "DOUB30": 0.0272, "DOUB31": 0.027200000000000002, "DOUB32": 0.0272, "DOUB33": 0.027200000000000002, "DOUB34": 0.0272, "DOUB35": 0.0272, "DOUB36": 0.0272}]'
```

---

I guess, the best option here is to avoid dealing with conversion of DOUBLE values altogether and go with DECIMAL instead.

Anyway, I'll look into some basic implementation of `csv_cols` with validation via REGEXP.

**Comment by wildraid** [comment] 2020-05-30 09:34
@RomantsovArtur , please update to version `0.13.0` and try the following syntax:

```
import_params = {
    'csv_cols': ["1..57", "58 FORMAT='999999999999999.999999'", "59..93"]
}

conn.import_from_file(file_obj, update_table_name, import_params)
```

Please let me know if it works for you :)

**Comment by RomantsovArtur** [comment] 2020-06-02 13:42
Thank you very much for this. I will check it today or early tomorrow

**Comment by RomantsovArtur** [comment] 2020-06-03 08:51
Works as it should. Great !

**Closed** 2020-06-03 10:28 UTC
